### ISSUE TITLE
‘reset_envs’ was not declared in this scope

### ISSUE THREAD

**Issue by ravihammond** [gfppoy/hanabi-br-withbelief#1]
Hi gfppoy!

I'm trying to compile this repo, and I'm getting the following error at [this line](https://github.com/gfppoy/hanabi-br-withbelief/blob/7a7e7ddf53c6764bd780607937ced06ef9e613f1/cpp/thread_loop.h#L51).
`error: ‘reset_envs’ was not declared in this scope`

I grepped through the repo, and I can't find the `reset_envs` variable declared anywhere else.

If possible, could you help me fix this issue, an point me in the right direction to get this repo compiling?

Many thanks,
Ravi

**Comment by gfppoy** [comment]
Hi Ravi, thanks very much for bringing this up, there was a versioning issue present. If you pull the changes I've made should be compilable now.
